### ISSUE TITLE
Core contract infrastructure

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#1]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/optimism/issues/2
- [x] Do we use Optimism's forge setup to compile contracts?
- [x] Add first Celo core contract to repo and make it compile
- [x] Decide what existing deployment testing and tooling should be moved over and minimally create tickets for this
```

See https://github.com/ethereum-optimism/optimism/compare/develop...karlb:optimism:karlb/celo-registry?expand=1 for an incomplete experiment of deploying a Celo contract the Optimism way.
