### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#10]
We usually use GitHub Actions, but since upstream uses CircleCI it might make sense to stay with it to avoid migration and maintenance work.

```[tasklist]
### Tasks
- [x] Decide on CircleCI vs GithHub Actions
- [ ] https://github.com/celo-org/op-geth/issues/2
- [ ] https://github.com/celo-org/optimism/issues/12
- [ ] https://github.com/celo-org/optimism/issues/31
- [ ] https://github.com/celo-org/op-geth/issues/6
- [x] Fix remaining failing tests
```
