### ISSUE TITLE
Governable Block Size

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#105]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/314
- [ ] https://github.com/celo-org/optimism/issues/132
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/192
```

**Comment by tynes** [comment]
Right now the L2 gas limit is set in the `SystemConfig` contract, its an `Ownable` contract. Curious if this works for you? We could consider adding a more RBAC based solution where different accounts can modify different variables, or this could be done via an external contract that owns the `SystemConfig`

**Comment by soloseng** [comment]
Currently works as is. We don't really have anything that would depend on this and consider it purely informational.
