### ISSUE TITLE
Improve state migration tool (`celo-migrate`)

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#108]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/optimism/issues/135
- [ ] https://github.com/celo-org/optimism/issues/143
- [ ] https://github.com/celo-org/optimism/issues/142
- [x] Disable OP governance for L2 OP deployment
- [x] Run `DeployConfig.Check` earlier to provide better errors
```

**Comment by palango** [comment]
Merged remaining tasks in https://github.com/celo-org/optimism/issues/169
