### ISSUE TITLE
FeeHandler/UltraGreen

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#11]
Implement [CIP-52](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0052.md) or an adaptation of it.
```[tasklist]
### Tasks
- [x] Send base fee to FeeHandler contract
- [x] Add FeeHandler contract
- [ ] https://github.com/celo-org/optimism/issues/78
```

**Comment by karlb** [comment]
> Send base fee to FeeHandler contract

If we have the FeeHandler at a fixed address (and I don't see why we shouldn't), we can just set the `OptimismBaseFeeRecipient` at https://github.com/celo-org/op-geth/blob/0c10250b1e8a67815b85e59a9b3502e94b5368a5/params/protocol_params.go#L27 and be done with it.

**Comment by carterqw2** [comment]
Nice one!
