### ISSUE TITLE
Setup deployment for OP stack components

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#13]
We need to run the components of the OP stack for the testnet and figure out how to do this best.

- [OP network setup docs](https://stack.optimism.io/docs/build/getting-started/#run-the-node-software)
- [compose file for OP devnet](https://github.com/ethereum-optimism/optimism/blob/develop/ops-bedrock/docker-compose.yml)

```[tasklist]
### Tasks
- [x] Decide how to run those services and configure infrastructure
- [x] Generate [L2 config files](https://stack.optimism.io/docs/build/getting-started/#generate-the-l2-config-files)
- [x] (optional) Enable basic monitoring for the testnet
- [x] Ensure the Sepolia RPC does not run out of quota (get premium account?)
```
