### ISSUE TITLE
Proposal for accessing old state after migration

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/optimism#14]
Requirements for this needs external input from product/business.

```[tasklist]
### Tasks
- [ ] proposal/design doc around what we will provide
- [ ] doc should include technical implementation path
- [ ] tickets created to capture this work
```
