### ISSUE TITLE
Deploy OP stack for testnet

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#15]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/optimism/issues/3
- [ ] https://github.com/celo-org/optimism/issues/4
- [ ] https://github.com/celo-org/optimism/issues/13
```
