### ISSUE TITLE
Proposal for governance mechanics on the OP stack

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/optimism#16]
Needs support from primitives team.

```[tasklist]
### Tasks
- [ ] proposal/design doc for changes (if any) to governance scheme
- [ ] doc should include high-level technical implementation steps + migration path
- [ ] tickets created to capture this work
```

**Comment by palango** [comment]
@martinvol I guess we can close this, as we'll continue using Celo goverance.
