### ISSUE TITLE
`celo-migrate` script - M4

### ISSUE THREAD

**Issue by alecps** [celo-org/optimism#169]
The migration script will be used by many people and should be as easy and fool-proof to use as possible.

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/optimism/issues/171
- [ ] https://github.com/celo-org/optimism/issues/159
- [ ] https://github.com/celo-org/optimism/issues/173
- [ ] https://github.com/celo-org/optimism/issues/203
- [ ] https://github.com/celo-org/optimism/issues/201
- [ ] https://github.com/celo-org/optimism/pull/226
- [ ] https://github.com/celo-org/optimism/pull/233
```

**Comment by piersy** [comment]
need to split into ux and fixes epics

**Comment by alecps** [comment]
Just flagging that this epic is closely related to https://github.com/celo-org/celo-blockchain-planning/issues/419

**Comment by lvpeschke** [comment]
@alecps what's missing here at this point? Can this be closed before end of week?

**Comment by lvpeschke** [comment]
@alecps ping
