### ISSUE TITLE
Proposal for using only finalized Ethereum data

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/optimism#17]
High-level proposal has already been provided in [the forum post](https://forum.celo.org/t/clabs-proposal-for-celo-to-transition-to-an-ethereum-l2/6109). 

```[tasklist]
### Tasks
- [ ] design doc to more thoroughly spec out details (i.e. with specific parameters, considerations, risks) and obtain feedback
- [ ] doc should include how to handle extreme cases of Ethereum finalization (i.e. Gasper not finalizing for a long time)
- [ ] implementation plan + create tickets/next steps for continuing this work
```

**Comment by karlb** [comment]
See also https://github.com/ethereum-optimism/optimism/blob/38125b9203dc39dc0e0793c2745a94b9af2e529b/op-proposer/proposer/l2_output_submitter.go#L143-L147

**Comment by palango** [comment]
Closed for the mroe specific tasks in #84
