### ISSUE TITLE
Proposal for DA-integration

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/optimism#22]
High-level proposal has already been provided in [the forum post](https://forum.celo.org/t/clabs-proposal-for-celo-to-transition-to-an-ethereum-l2/6109). 

```[tasklist]
### Tasks
- [ ] design doc to more thoroughly spec out implementation steps
- [ ] firm decision on DA provider
- [ ] implementation plan + create tickets/next steps for continuing this work
```
