### ISSUE TITLE
Bridging Plan

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#29]
OP-Stack provides bridging ETH between L1 and L2 in both directions. By changing the native currency on L2 to CELO, we are breaking this mechanism, since it relies on having the same native currency across both layers.

We could bridge L1 ETH to L2 cETH and L2 CELO to L1 wrapped CELO.

```[tasklist]
### Tasks
- [x] Figure out the state of cETH on the Celo blockchain
- [x] Figure out the state of wrapped CELO on Ethereum
- [x] Check OP-Stack bridging to see if such cases are easily supported
- [x] Create followup issue(s)
```

See
* [L1StandardBridge](https://github.com/ethereum-optimism/optimism/blob/beeffe9cca7cbd2c8d9b82fe7bbdb292c3e103db/packages/contracts-bedrock/src/L1/L1StandardBridge.sol)
* [L2StandardBridge](https://github.com/ethereum-optimism/optimism/blob/beeffe9cca7cbd2c8d9b82fe7bbdb292c3e103db/packages/contracts-bedrock/src/L2/L2StandardBridge.sol)
* [Bridging tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token), [bridging tutorial (custom token)](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-custom-token)
* https://github.com/celo-org/celo-monorepo/issues/10167

**Comment by karlb** [comment]
The current wrapped ETH tokens on Celo are bridged through Axelar and Wormhole (two separate tokens). If we add native bridging, we would get a new ETH token on CELO (and use unwrapped ETH, if possible).

**Comment by karlb** [comment]
The default token contract for bridged tokens on the L2 is https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/universal/OptimismMintableERC20.sol. If we add `debitGasFee` and `creditGasFee`, we could use bridged tokens as fee currencies.

**Comment by karlb** [comment]
We decided to include only ETH bridging in this milestone. Bridging Celo has been split off into https://github.com/celo-org/optimism/issues/62.
