### ISSUE TITLE
Decide on L1 testnet, run nodes, get L1 Eth

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#3]
```[tasklist]
### Tasks
- [x] Chose a testnet to use as the L1, [Sepolia](https://github.com/eth-clients/sepolia) looks like the obvious choice
- [x] Setup custom node(s) or find a reliable service provider
- [x] Get a decent amount of L1 Eth for deployment and operations
- [x] Check if free alchemy account has sufficient quota to run testnet
```

### References
- https://ethereum.org/en/developers/docs/networks/

**Comment by karlb** [comment]
* Run on sepolia
* Use alchemy or infura to access the sepolia node
