### ISSUE TITLE
Deploy Faucet

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#54]
```[tasklist]
### Tasks
- [x] Create a feature branch of the Faucet app
- [x] Get a faucet account
- [ ] https://github.com/celo-org/optimism/issues/80
- [ ] https://github.com/celo-org/optimism/issues/81
- [x] Monitor faucet funds and alert on low funds
```

**Comment by carterqw2** [comment]
Blocked by https://celo-org.slack.com/archives/C0117G4T96W/p1695905547607849

**Comment by lvpeschke** [comment]
@carterqw2 the link in https://github.com/celo-org/optimism/issues/54#issuecomment-1753175109 is broken, could you explain the blocker?

**Comment by aaronmgdr** [comment]
@carterqw2 If we fund 0x22579CA45eE22E2E16dDF72D955D6cf4c767B0eF on the testnet with lots of celo (but not too much*) we can use existing setup. especially if the node url and chain id remain the same as alajores


* want to avoid draining the faucet and not having a source of funds to top up.

**Comment by aaronmgdr** [comment]
One TODO to add might be to add a low level alert on grafana when the faucet gets down to about 15,000 tokens. together with a way any eng at clabs can refill it

**Comment by aaronmgdr** [comment]
After talking it turns out that 

A) there is already alerting https://github.com/celo-org/devrel-x-product-clabs/issues/2.
B) since we are migrating instead of starting up from scratch that super faucet account will not exist 
C) since MintCeloTokenSchedule still sends funds to carbonOffsetFund the faucet will stll recieve new funds each time that is called. so yay. nothing to do here

**Comment by lvpeschke** [comment]
@aaronmgdr is https://github.com/celo-org/optimism/issues/81 still desirable? Should there be a task for updated documentation around the faucet?

**Comment by aaronmgdr** [comment]
I never thought 81 was needed. 

I dont see there being anything that must happen here.
