### ISSUE TITLE
Add ERC20 contract (mostly for testing)

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#56]
Subtask of #6 

For building and running tests of transaction with fee currencies, we need an ERC20 implementation. 

```[tasklist]
### Tasks
- [x] Find a suitable token with `credit` and `debit` functions
- [x] Add it to the https://github.com/celo-org/optimism repo
- [x] Adapt the import script and generate wrappers: https://github.com/celo-org/op-geth/tree/celo1/contracts/celo
```

**Comment by palango** [comment]
A suitable existing contract is `StableToken` from mento: https://github.com/mento-protocol/mento-core/blob/7c36d6031e0d1ed04582a38dd5de0c50f04d6cfc/contracts/StableToken.sol

But for that we need a plan on how to integrate the mento repo here, because we probably don't want to copy over the contract. (ping @pahor167)

**Comment by karlb** [comment]
> But for that we need a plan on how to integrate the mento repo here, because we probably don't want to copy over the contract. (ping @pahor167)

I would not mind copying it over. Sounds more straightforward than integrating another repository to me.

**Comment by karlb** [comment]
Here's a simple ERC20 + credit/debitGasFees functions: https://github.com/celo-org/optimism/pull/71

This is all we need, so we don't have to include Mento's big StableToken contract.
