### ISSUE TITLE
Add BaseGasPrice and exchange rates per currency to block context

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#58]
Subtask of #6 

For comparing legacy and celo transactions, we need access to the base gas prices and exchange rates. They should be added to the block context and only be created once per block.
This might partly be done or required for #53 .

```[tasklist]
### Tasks
- [x] Decide whether to add this directly to the `BlockContext` or add an additional struct like `FeeCurrencyContext`
- [x] Add this to the block context
- [x] Make sure this context is set up at block creation
```

**Comment by karlb** [comment]
Depends on discussion in https://www.notion.so/clabsco/ERC20-fee-currencies-for-CEL2-7fbf7c53e52c4cacab6e8e61d290fe93
