### ISSUE TITLE
ERC20 fee currencies

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#6]
- Includes decision about tx types to bring to the L2 (will impact how well tools like forge and hardhat will be able to fork a Celo chain)
- Includes decision around governable Whitelisting ERC20 parameters, decision around `IntrinsicGasForAlternativeFeeCurrency` being governable or requiring HF
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/optimism/issues/47
- [ ] https://github.com/celo-org/optimism/issues/58
- [ ] celo-org/optimism#56
- [ ] https://github.com/celo-org/optimism/issues/57
- [ ] https://github.com/celo-org/optimism/issues/59
- [ ] https://github.com/celo-org/optimism/issues/75
- [ ] https://github.com/celo-org/optimism/issues/53
- [ ] https://github.com/celo-org/optimism/issues/61
- [ ] https://github.com/celo-org/optimism/issues/72
- [ ] https://github.com/celo-org/optimism/issues/86
- [ ] https://github.com/celo-org/optimism/issues/91
```

**Comment by karlb** [comment]
Are there any changes we want to make with regards to how we interface with the ERC20 contracts? @pahor167 @martinvol

**Comment by pahor167** [comment]
> Are there any changes we want to make with regards to how we interface with the ERC20 contracts? @pahor167 @martinvol

As discussed on a meeting. It seem that Hardhat is whitelisting transaction fields. Since we will be keeping extra fields in transaction it seems that Hardhat will not work out of the box. Foundry on the other hand should be able to handle that.
