### ISSUE TITLE
Bridge ETH to L2

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#63]
The current wrapped ETH tokens on Celo are bridged through Axelar and Wormhole (two separate tokens). If we add native bridging, we would get a new ETH token on CELO (and use unwrapped ETH, if possible).

The default token contract for bridged tokens on the L2 is https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/universal/OptimismMintableERC20.sol. If we add `debitGasFee` and `creditGasFee`, we could use bridged tokens as gas currencies (see https://github.com/celo-org/celo-blockchain-planning/issues/902).

See
* [L1StandardBridge](https://github.com/ethereum-optimism/optimism/blob/beeffe9cca7cbd2c8d9b82fe7bbdb292c3e103db/packages/contracts-bedrock/src/L1/L1StandardBridge.sol)
* [L2StandardBridge](https://github.com/ethereum-optimism/optimism/blob/beeffe9cca7cbd2c8d9b82fe7bbdb292c3e103db/packages/contracts-bedrock/src/L2/L2StandardBridge.sol)
* [Bridging tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token), [bridging tutorial (custom token)](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-custom-token)
```[tasklist]
### Tasks
- [x] Deploy ERC20 token for ETH on L2
- [x] Bridge L1 ETH to an ERC20 token on L2
- [x] Bridge ERC20 ETH from L1 to L1 ETH
- [x] Add test
- [ ] Adapt existing optimism bridging tests
```
