### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#79]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/optimism/issues/3
- [ ] https://github.com/celo-org/optimism/issues/4
- [ ] https://github.com/celo-org/optimism/issues/15
- [ ] https://github.com/celo-org/optimism/issues/2
- [ ] https://github.com/celo-org/optimism/issues/10
- [ ] https://github.com/celo-org/optimism/issues/31
- [ ] https://github.com/celo-org/optimism/issues/13
- [ ] https://github.com/celo-org/optimism/issues/12
```
