### ISSUE TITLE
CELO as native token

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#8]
In addition to the token duality, which changes are needed to use Celo as a native token? The main point is that the native token will differ between L1 and L2.

```[tasklist]
- [ ] https://github.com/celo-org/optimism/issues/29
- [ ] https://github.com/celo-org/optimism/issues/63
- [x] Which DA cost do we assume for now?
- [x] How do L2 gas fees get calculated?
- [x] Do we have to rename ETH to CELO in certain places of the code (external APIs)?
```

From https://forum.celo.org/t/clabs-proposal-for-celo-to-transition-to-an-ethereum-l2/6109/2#celo-tokens-as-native-currency-on-l2-9:

> The OP Stack uses ETH to pay gas fees on L2. If the Celo blockchain chooses to become an L2 based on the OP Stack, the CELO token must be the native currency and be used to pay gas fees on L2. Alternative fee currencies (e.g. ETH) will still be available in the same way they currently are on the Celo blockchain. All of this is important to maintain compatibility with existing Celo applications and preserve the Celo token economics.
>
> Paying gas fees on L2 in a different currency than on L1 can have implications in places where both layers interact. So these interactions must be checked and adapted if necessary:
> 
> L2 transaction costs: On Optimism, transactions incur an L1 data fee in addition to the normal gas fee. This fee is used to cover the costs of making the transaction data available on L1. The calculation of the data fee needs to be adapted for multiple reasons:
> 
> * Using EigenDA for data availability has a different cost structure than using Ethereum as a DA layer (see [Off-chain Data Availability with EigenDA](https://forum.celo.org/t/clabs-proposal-for-celo-to-transition-to-an-ethereum-l2/6109/2#off-chain-data-availability-with-eigenda-7)).
> * Reading L1 gas prices only from finalized blocks increases the time between reading L1 gas prices and writing to L1, thereby increasing the risk of significant price changes (see [1-Block Finality](https://forum.celo.org/t/clabs-proposal-for-celo-to-transition-to-an-ethereum-l2/6109/2#h-1-block-finality-3)).
> * Using different gas currencies on L1 and L2 adds exchange rate risks.
> 
> Luckily, there are also factors at play that mitigate these difficulties:
> 
> * By using EigenDA, the L1 costs for data availability are greatly reduced (and with it the exchange rate and L1 gas price volatility risk).
> * EigenDA can be configured to use CELO tokens to pay data provider nodes, avoiding all risks related to CELO/ETH conversion.
> * The sequencer has a strong incentive to make transaction data available even if the cost of doing so goes somewhat beyond the earned data fees, because it will be slashed if it fails to provide the data (see [1-Block Finality](https://forum.celo.org/t/clabs-proposal-for-celo-to-transition-to-an-ethereum-l2/6109/2#h-1-block-finality-3)). It is sufficient that the economics work out on average.
> 
> It is too early to decide on a specific formula for the data fee, but the rough structure will be
> 
> celo_data_fee = tx_data_size * eigenda_data_price
> eth_data_fee = eigenda_certificate_size * L1_gas_price
> total_data_fee (in CELO) = celo_data_fee + eth_data_fee * exchange_rate * safety_margin
> 
> Celo already successfully uses oracles to convert between different gas currencies and the native CELO token, so retrieving an exchange rate between ETH and CELO via a similar mechanism should not be a problem.
> 
> Purchasing guaranteed L2 gas on L1: Optimism allows depositing transactions on L1 to force execution of these transactions in L2. The L2 gas required for execution is paid for by burning ETH on L1 at a price which is determined by an EIP-1559 market. Since this market sells gas directly, without going through the L2 gas price, the L2 gas currency is not involved at all. So no changes are necessary due to using CELO tokens as a gas currency on L2.

**Comment by karlb** [comment]
> Which DA cost do we assume for now?

Same as optimism.

> How do L2 gas fees get calculated?

Same as optimism for now.

Both of these will change once we move to a different DA solution.
