### ISSUE TITLE
State Migration Tool

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#83]
Blocked by #123 

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/optimism/issues/7
- [ ] https://github.com/celo-org/optimism/issues/65
- [ ] https://github.com/celo-org/optimism/issues/9
- [ ] https://github.com/celo-org/optimism/issues/36
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/181
- [ ] https://github.com/celo-org/optimism/issues/134
- [ ] https://github.com/celo-org/optimism/issues/141
- [ ] https://github.com/celo-org/optimism/issues/155
- [ ] https://github.com/celo-org/optimism/issues/157
- [ ] https://github.com/celo-org/optimism/issues/158
- [ ] https://github.com/celo-org/optimism/issues/160
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/347
```

**Comment by lvpeschke** [comment]
End of weekly commitment check-in: @palango can you provide a status update?

**Comment by palango** [comment]
PR is ready and waiting for review: https://github.com/celo-org/optimism/pull/138

**Comment by lvpeschke** [comment]
End of weekly commitment check-in: @palango what's the current ETA? Is #141 the last thing left & in progress?

**Comment by palango** [comment]
#141 is now solved in https://github.com/celo-org/op-geth/pull/149

But new issues keep coming up, so it's not done yet.

**Comment by palango** [comment]
All necessary tasks for state migration are done. Improvements are tracked in https://github.com/celo-org/optimism/issues/169
