### ISSUE TITLE
1-block Finality

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#84]
Initial analysis on https://clabsco.slack.com/archives/CNJ7KTHQU/p1719478411189299

```[tasklist]
### Research, design, documentation
- [ ] https://github.com/celo-org/optimism/issues/17
- [ ] https://github.com/celo-org/optimism/issues/103
- [ ] https://github.com/celo-org/optimism/issues/207
- [ ] https://github.com/celo-org/optimism/issues/195
```

```[tasklist]
### Implementation - 40h total?
- [ ] https://github.com/celo-org/optimism/issues/198
- [ ] https://github.com/celo-org/optimism/issues/200
```

**Comment by lvpeschke** [comment]
@palango do you have an estimation for this epic? (https://clabsco.slack.com/archives/C0705GMH2A1/p1715949226812009?thread_ts=1715879939.704039&cid=C0705GMH2A1)

**Comment by lvpeschke** [comment]
Currently blocked on finishing the state migration https://github.com/celo-org/optimism/issues/83 (human bandwidth).

**Comment by lvpeschke** [comment]
Related: https://clabsco.slack.com/archives/CNJ7KTHQU/p1719478411189299

**Comment by piersy** [comment]
Can we add it to, dango retrospectively? (or would that require a contract re-deploy do we need to have a hardfork style upgrade)

We already announced that dango has 1 block finality!

**Comment by piersy** [comment]
Despite a potential refactor of the derivation pipeline from protolambda, we want to go forward with this.

**Comment by palango** [comment]
Alfajores scope has been done, issues for M5 are tracked in https://github.com/celo-org/celo-blockchain-planning/issues/621
