### ISSUE TITLE
Full Celo Features Migration

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#85]
```[tasklist]
### Tasks
- [ ] Migrate existing Governance
- [ ] Migrate/remove fractionMulExp precompile
- [ ] Migrate Governable Block Size
```
