### ISSUE TITLE
Fee currencies cleanup

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#93]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/op-geth/issues/70
- [ ] https://github.com/celo-org/op-geth/issues/73
- [ ] https://github.com/celo-org/op-geth/issues/75
- [ ] https://github.com/celo-org/op-geth/issues/76
```

See also:
- https://github.com/celo-org/op-geth/issues/69
- https://github.com/celo-org/op-geth/issues/72
- https://github.com/celo-org/op-geth/issues/74
